- name: Create backup directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0755'

- name: Get current timestamp
  shell: date +%Y%m%d_%H%M%S
  register: timestamp

- name: Backup WordPress database using shell
  shell: >
    mysqldump
    --user={{ mysql_user }}
    --password={{ mysql_password }}
    --host={{ mysql_host }}
    {{ mysql_db }} | gzip > {{ backup_dir }}/wordpress_{{ timestamp.stdout }}.sql.gz
  args:
    executable: /bin/bash

- name: Upload backup to FTP server
  shell: |
    curl -T {{ backup_dir }}/wordpress_{{ timestamp.stdout }}.sql.gz \
    ftp://{{ ftp_user }}:{{ ftp_password }}@{{ ftp_host }}{{ ftp_path }}/
  args:
    executable: /bin/bash

- name: Remove local backup file
  file:
    path: "{{ backup_dir }}/wordpress_{{ timestamp.stdout }}.sql.gz"
    state: absent

- name: Clean old backups from FTP server
  shell: |
    lftp -u {{ ftp_user }},{{ ftp_password }} {{ ftp_host }} -e "cd {{ ftp_path }}; \
    cls -1 --date | awk '{if (systime()-$4 > 432000) print $6}' | \
    while read file; do rm -f \"$file\"; done; quit"
  args:
    executable: /bin/bash
  ignore_errors: true
